name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: docker://continuumio/miniconda3:4.7.12
    - run: conda install -q -y -c conda-forge tectonic
    - run: env
    - run: which tectonic
    - uses: actions/checkout@v1
    - run: cd tex && tectonic jupyterhub-evaluation-whitepaper.tex && cd ..
    - run: mkdir -p pdf_out/
    - run: mv tex/jupyterhub-evaluation-whitepaper.pdf pdf_out/.
    - uses: actions/upload-artifact@v1
      with:
        name: jupyterhub-evaluation-whitepaper.pdf
        path: pdf_out/
