name: Build PDF

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    container: docker://pandoc/latex:latest
    steps:
    - uses: actions/checkout@v1
    - run: echo ${GITHUB_SHA} && pandoc -f markdown+implicit_figures --pdf-engine=xelatex --variable fontsize=12pt --toc -o jupyterhub-white-paper_${GITHUB_SHA}.pdf white-paper.md && ls -la
    - uses: actions/upload-artifact@v2
      with:
        name: jupyterhub-white-paper.zip
        path: jupyterhub-white-paper_${{github.sha}}.pdf
        if-no-files-found: error
