name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: docker://danteev/texlive:v1.6.0
    steps:
    - uses: actions/checkout@v1
    - run: cd tex/ && latexmk -bibtex -pdf jupyterhub-evaluation-whitepaper.tex -pdflatex="pdflatex --shell-escape %O %S" && cd -
    - uses: actions/upload-artifact@v1
      with:
        name: jupyterhub-evaluation-whitepaper.pdf
        path: tex/jupyterhub-evaluation-whitepaper.pdf
