name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: docker://exaesmwp4/texlive:latest
    steps:
    - uses: actions/checkout@v1
    - run: cd tex/ && latexmk -f -bibtex -pdf -pdflatex="pdflatex --shell-escape %O %S" jupyterhub-evaluation-whitepaper.tex && cd -
    - uses: actions/upload-artifact@v1
      with:
        name: jupyterhub-evaluation-whitepaper.pdf
        path: tex/jupyterhub-evaluation-whitepaper.pdf
