name: Build PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    container: docker://pandoc/latex:latest
    steps:
    - uses: actions/checkout@v2
    - run: pandoc -f markdown+implicit_figures --pdf-engine=xelatex --variable fontsize=12pt --toc -o jupyterhub-white-paper_${{github.event.pull_request.head.sha}}.pdf white-paper.md && ls -la
    - uses: actions/upload-artifact@v2
      with:
        name: jupyterhub-white-paper
        path: jupyterhub-white-paper_${{github.event.pull_request.head.sha}}.pdf
        if-no-files-found: error
